apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keel-test
  namespace: flux-system
spec:
  interval: 5m
  path: ./deployments
  prune: true
  sourceRef:
    kind: GitRepository
    name: keel-test

