apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: hello-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-repo
  filterTags:
    pattern: '^test$'
  policy:
    alphabetical:
      order: asc

